version: "3.8"
   
services:
     

    web:
        build: .
        container_name: django2
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - app_data:/usr/src/app/
        ports:
            - "8000:8000"
        env_file:
            - ./env.dev
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

        depends_on:
            - pgdb
            - redis
    celery:
        restart: always
        build: 
            context: .
        command: celery -A wine_shop worker -l DEBUG
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] 
        depends_on:
            - web
            - redis
        container_name: celery
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
    # Redis
    redis:
        image: redis:alpine
        container_name: redis
   
        
volumes:
    pgdata:
    app_data:
