version: "3.8"
   
services:
     

    web:
        build: .
        container_name: django2 
        command: >
            sh -c "python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        volumes:
            - app_data:/usr/src/app/
        ports:
            - "8000:8000"
        env_file:
            - ./env.dev
        

        depends_on:
            - pgdb
           # - rabbitmq
    # celery:
    #     restart: always
    #     build: 
    #         context: .
    #     container_name: celery
    #     command: celery -A wine_shop worker -l info
    #     volumes:
    #         - .:/usr/src/app
    #     env_file:
    #         - ./.env.dev

    #     depends_on:
    #         - pgdb
    #         - web
    #         - rabbitmq
    pgdb:
        image: postgres
        container_name: pgdb
        env_file:
            - ./.env.dev
        volumes:
            - pgdata:/var/lib/postgresql/data/

    # rabbitmq:
    #     image: rabbitmq:3.7-alpine
    #     container_name: 'rabbitmq'



volumes:
    pgdata:
    app_data:
