# Generated by Django 4.0.5 on 2022-09-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Court',
            new_name='Coupon',
        ),
    ]
