# Generated by Django 4.0.5 on 2022-09-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_court_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='activate',
            new_name='active',
        ),
    ]
