# Generated by Django 4.0.6 on 2022-08-02 09:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('new_old_world', models.CharField(choices=[('New World', 'New World'), ('Old World', 'Old World')], max_length=10)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='shop.country')),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('vintage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2022)])),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('wine_producer', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine', to='shop.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine', to='shop.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine', to='shop.region')),
            ],
            options={
                'ordering': ['wine_name'],
            },
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['country'], name='shop_countr_country_5ddf2c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='shop_catego_name_289c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['id', 'slug'], name='shop_wine_id_2c1622_idx'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['wine_name'], name='shop_wine_wine_na_0d20a5_idx'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['-created'], name='shop_wine_created_0c780f_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['country'], name='shop_region_country_efa7d5_idx'),
        ),
    ]
