# Generated by Django 4.1 on 2024-04-01 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_wine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='vintage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
