# Generated by Django 4.1 on 2022-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
