# Generated by Django 4.1 on 2022-08-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, default=1232, max_length=250),
            preserve_default=False,
        ),
    ]
